"use client";

import Link from "next/link";
import { ShieldAlert, ArrowLeft, PhoneCall, CheckCircle } from "lucide-react";
import { PageTitle } from "@/components/ui/page-title";

export default function MedicalDisclaimerPage() {
  return (
    <div className="space-y-8 max-w-4xl mx-auto">
      <div className="flex items-center gap-2">
        <Link
          href="/"
          className="inline-flex items-center gap-1.5 text-xs font-semibold text-slate-500 hover:text-slate-900 transition-colors"
        >
          <ArrowLeft className="h-3.5 w-3.5" />
          Back to Dashboard (डैशबोर्ड)
        </Link>
      </div>

      <PageTitle
        eyebrow="Medical Safety Notice (चिकित्सीय अस्वीकरण)"
        title="Medical Disclaimer"
        description="Important information regarding the purpose, scope, and non-clinical nature of SwasthTrack."
      />

      {/* CORE HIGHLIGHT BOX */}
      <div className="rounded-2xl border-2 border-emerald-300 bg-emerald-50/70 p-6 sm:p-7 space-y-3">
        <div className="flex items-center gap-2.5">
          <ShieldAlert className="h-6 w-6 text-emerald-700 shrink-0" />
          <h2 className="text-base sm:text-lg font-black text-slate-900">
            For Informational &amp; Personal Tracking Purposes Only
          </h2>
        </div>
        <p className="text-sm text-slate-800 leading-relaxed font-medium">
          SwasthTrack is a digital health tracking and daily wellness companion designed to help patients and families keep organized personal records of their health routines.
        </p>
        <p className="text-sm text-slate-800 leading-relaxed font-bold">
          SwasthTrack is NOT a medical device, hospital, licensed diagnostic laboratory, doctor, or emergency medical service provider.
        </p>
      </div>

      {/* DETAILED DISCLAIMER SECTIONS */}
      <div className="rounded-2xl border border-slate-200 bg-white p-6 sm:p-8 space-y-6 text-xs sm:text-sm text-slate-700 leading-relaxed">
        {/* 1. Not a Substitute for Medical Advice */}
        <section className="space-y-2">
          <h3 className="text-base font-bold text-slate-900">
            1. No Substitute for Professional Healthcare
          </h3>
          <p>
            The content, charts, alerts, scores (e.g., Wellness Score), and summaries provided by SwasthTrack are for educational and tracking convenience only. They are not intended to be a substitute for professional medical advice, diagnosis, or treatment.
          </p>
          <p>
            Always seek the advice of your physician or qualified healthcare provider with any questions you may have regarding a medical condition, symptoms, or treatment plan.
          </p>
        </section>

        {/* 2. Medication & Prescription Decisions */}
        <section className="space-y-2">
          <h3 className="text-base font-bold text-slate-900">
            2. Prescriptions and Medications
          </h3>
          <p>
            Never disregard professional medical advice or delay seeking it because of something you have recorded or read on SwasthTrack.
          </p>
          <ul className="list-disc list-inside space-y-1 pl-1 text-slate-800 font-medium">
            <li>Do NOT start, stop, or change the dosage or timing of any prescribed medication based on app metrics or scores.</li>
            <li>All prescription modifications must be made directly by your treating doctor.</li>
          </ul>
        </section>

        {/* 3. Predictive Insights & Estimates */}
        <section className="space-y-2">
          <h3 className="text-base font-bold text-slate-900">
            3. Pattern Insights & Estimates
          </h3>
          <p>
            Any trend insights, anomaly flags, or calorie calculations generated by the application are statistical estimates derived from user-entered logs. They carry inherent mathematical uncertainties and do not represent verified clinical assessments.
          </p>
        </section>

        {/* 4. Emergency Situations */}
        <section className="rounded-xl border border-rose-200 bg-rose-50/70 p-5 space-y-3">
          <div className="flex items-center gap-2 text-rose-900 font-bold text-sm">
            <PhoneCall className="h-4 w-4 text-rose-600 shrink-0" />
            <span>Medical Emergencies</span>
          </div>
          <p className="text-xs sm:text-sm text-rose-950 leading-relaxed font-medium">
            If you or your family member believe you are experiencing a medical emergency (such as severe chest pain, shortness of breath, sudden numbness, weakness in the face or arms, speech difficulty, or an extreme hypertensive spike):
          </p>
          <div className="rounded-lg bg-white/80 border border-rose-200 p-3 text-rose-900 font-bold text-center text-sm">
            🚨 Call your local emergency medical service immediately (e.g. 112 / 108 in India) or visit the nearest hospital emergency room.
          </div>
        </section>

        {/* 5. Doctor Checkup Reports */}
        <section className="space-y-2">
          <h3 className="text-base font-bold text-slate-900 flex items-center gap-2">
            <CheckCircle className="h-4 w-4 text-emerald-600" />
            5. Use During Doctor Visits
          </h3>
          <p>
            We encourage you to export and share your SwasthTrack logs (Blood Pressure history, medicine adherence logs, and weight trends) with your doctor during routine clinical appointments to give them an organized record of your at-home daily health patterns.
          </p>
        </section>
      </div>
    </div>
  );
}
